f150:
  center: 150
  width: 40
  shape: top_hat
  time_constant: 0
  NEP: 3.e-5 # pW / sqrt(s)
  knee: 1.0 # Hz
  efficiency: 0.5
  gain_error: 5.e-2

f220:
  center: 220
  width: 40
  shape: top_hat
  time_constant: 0
  NEP: 3.e-5 # pW / sqrt(s)
  knee: 1.0 # Hz
  efficiency: 0.5
  gain_error: 5.e-2

f270:
  center: 270
  width: 50
  shape: gaussian
  time_constant: 0
  NEP: 3.e-5 # pW / sqrt(s)
  knee: 1.0 # Hz
  efficiency: 0.5
  gain_error: 5.e-2
