default_context:
  full_name: "Thomas Morris"
  email: "thomasmorris@princeton.edu"
  github_username: "thomaswmorris"
  project_name: "maria"
  package_dist_name: "maria"
  package_dir_name: "maria"
  repo_name: "maria"
  project_short_description: "Ground-based telescope simulations."
  minimum_supported_python_version: "3.8"
replay_dir: "~/tmp/new-repo"
