f042:
  center: 42.e+9
  width: 24.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 45.846e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f092:
  center: 91.5e+9
  width: 51.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 59.784e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f151:
  center: 151.e+9
  width: 62.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 68.996e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f217:
  center: 217.e+9
  width: 69.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 91.430e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f288:
  center: 288.e+9
  width: 73.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 103.844e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f350:
  center: 350.e+9
  width: 50.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 154.693e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f403:
  center: 403.e+9
  width: 38.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 155.810e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f654:
  center: 654.e+9
  width: 118.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 496.369e-18 # W / sqrt(s)
  knee: 1.0 # Hz

f846:
  center: 845.5e+9
  width: 119.e+9
  shape: top_hat
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 512.703e-18 # W / sqrt(s)
  knee: 1.0 # Hz
