f027:
  center: 27.e+9
  width: 5.e+9
  shape: gaussian
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 3.e-17 # W / sqrt(s)
  knee: 1.0 # Hz

f039:
  center: 39.e+9
  width: 5.e+9
  shape: gaussian
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 3.e-17 # W / sqrt(s)
  knee: 1.0 # Hz

f093:
  center: 93.e+9
  width: 10.e+9
  shape: gaussian
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 3.e-17 # W / sqrt(s)
  knee: 1.0 # Hz

f150:
  center: 150.e+9
  width: 10.e+9
  shape: gaussian
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 3.e-17 # W / sqrt(s)
  knee: 1.0 # Hz

f225:
  center: 225.e+9
  width: 30.e+9
  shape: gaussian
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 3.e-17 # W / sqrt(s)
  knee: 1.0 # Hz

f280:
  center: 280.e+9
  width: 40.e+9
  shape: gaussian
  time_constant: 0
  efficiency: 0.5
  gain_error: 5.e-2
  NEP: 3.e-17 # W / sqrt(s)
  knee: 1.0 # Hz
