pa4:
  n: 397
  focal_plane_offset: [-0.8, -0.5]
  field_of_view: 1.0
  shape: hexagon
  bands: [act/pa4/f150, act/pa4/f220]
  primary_size: 6
  polarized: True

pa5:
  n: 397
  focal_plane_offset: [0.0, 1.0]
  field_of_view: 1.0
  shape: hexagon
  bands: [act/pa5/f090, act/pa5/f150]
  primary_size: 6
  polarized: True

pa6:
  n: 397
  focal_plane_offset: [0.8, -0.5]
  field_of_view: 1.0
  shape: hexagon
  bands: [act/pa6/f090, act/pa6/f150]
  primary_size: 6
  polarized: True
