
AtLAST:
  aliases: ["atlast"]
  description: Atacama Large Aperture Submillimeter Telescope
  arrays:
  - atlast/wafer-f042
  - atlast/wafer-f092
  - atlast/wafer-f151
  - atlast/wafer-f217
  - atlast/wafer-f288
  - atlast/wafer-f350
  - atlast/wafer-f403
  - atlast/wafer-f654
  - atlast/wafer-f846
  documentation: https://greenbankobservatory.org/science/gbt-observers/mustang-2/
