
AtLAST:
  aliases: ["atlast"]
  description: Atacama Large Aperture Submillimeter Telescope
  array:
    primary_size: 50 # in meters
    n: 217
    field_of_view: 0.07
    array_shape: hex
    bath_temp: 100.e-3 # in K
    bands: [atlast/f027, atlast/f039, atlast/f093, atlast/f150, atlast/f225, atlast/f280]
  documentation: https://greenbankobservatory.org/science/gbt-observers/mustang-2/
