AtLAST-M2-like:
  aliases: ["atlast","atlast-m2"]
  description: Atacama Large Aperture Submillimeter Telescope
  array:
    primary_size: 50 # in meters
    n: 217
    field_of_view: 0.07
    shape: hexagon
    bath_temp: 100.e-3 # in K
    bands: [atlast/f042, atlast/f093, atlast/f150, atlast/f220, atlast/f280, atlast/f350, atlast/f400, atlast/f650, atlast/f850]
  documentation: https://www.atlast.uio.no/

AtLAST-SZ:
  aliases: ["atlast-sz"]
  description: Atacama Large Aperture Submillimeter Telescope SZcam
  arrays:
    array-0:
      primary_size: 50 # in meters
      field_of_view: 2.0
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f042]
    array-1:
      primary_size: 50 # in meters
      field_of_view: 2.0
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f093, atlast/f150]
    array-2:
      primary_size: 50 # in meters
      field_of_view: 1.1
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f220, atlast/f280]
    array-3:
      primary_size: 50 # in meters
      field_of_view: 0.8
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f350, atlast/f400]
    array-4:
      primary_size: 50 # in meters
      field_of_view: 0.3
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f650, atlast/f850]
  documentation: https://ui.adsabs.harvard.edu/abs/2025ORE.....4..113D/abstract


AtLAST-SZ_mini:
  aliases: ["atlast-sz_mini"]
  description: Atacama Large Aperture Submillimeter Telescope SZcam-lite
  arrays:
    array-0:
      primary_size: 50 # in meters
      field_of_view: 0.13
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f042]
    array-1:
      primary_size: 50 # in meters
      field_of_view: 0.13
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f093, atlast/f150]
    array-2:
      primary_size: 50 # in meters
      field_of_view: 0.13
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f220, atlast/f280]
    array-3:
      primary_size: 50 # in meters
      field_of_view: 0.13
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 1.7 # f-lambda
      polarized: True,
      bands: [atlast/f350, atlast/f400]
    array-4:
      primary_size: 50 # in meters
      field_of_view: 0.13
      shape: circle
      bath_temp: 100.e-3 # in K
      beam_spacing: 3.4 # f-lambda
      polarized: True,
      bands: [atlast/f650, atlast/f850]
  documentation: https://www.atlast.uio.no/
